# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 166da2166ed48d7bec8649084924ff794dd2b97076df95412def6e61993f07d71d3c77762a2fc0665bdaac3b3993a763ff5962991a4b886909660661f363c688

test:
  secret_key_base: 277ee49f39f325fcdfbc098416294973b4a6020fdc71e6d2592b9024e21fa5c041201f1201c4789b1f4754a004b0b9073c9f370b8fb636996aae0cc75bd43cdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
